services:
    nginx:
        container_name: tanuki_nginx
        image: nginx:alpine
        ports:
            - "${DOCKER_APP_PORT:-80}:80"
        environment:
            APP_HOST: "${DOCKER_APP_HOST:-localhost}"
        volumes:
            - ./docker/nginx/server.nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./public:/var/www/html/public
            - ./storage/app/public:/var/www/html/storage/app/public
        networks:
            - tanuki
        depends_on:
            - app

    app:
        container_name: tanuki_app
        ports:
            - "${FORWARD_SOCKET_PORT:-8080}:8080"
        build:
            dockerfile: docker/php/Dockerfile
            context: .
        image: tanuki_app
        volumes:
            - ./:/var/www/html
            - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/99-xdebug.ini
        networks:
            - tanuki
        depends_on:
            - mysql

    mysql:
        container_name: tanuki_mysql
        image: mysql:8.3
        ports:
            - "${DOCKER_MYSQL_PORT:-3306}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: SwclxSQDa_jdFp6m6hz2
            MYSQL_USER: ${DB_USERNAME:-tanuki}
            MYSQL_PASSWORD: ${DB_PASSWORD:-6RR5Vr1hcain_SArm_i2}
            MYSQL_DATABASE: ${DB_DATABASE:-tanuki_db}
        volumes:
            - mysql_db_data:/var/lib/mysql
        networks:
            - tanuki

volumes:
    mysql_db_data:
        name: tanuki_mysql_db_data
        external: false

networks:
    tanuki:
        name: tanuki
        driver: bridge
